### ISSUE TITLE
Typo error in template

### ISSUE THREAD

**Issue by DarkArc-Github** [karmafeast/win_dhcp_server#1]
There's a typo error in template **command-win_dhcp_server_conflict_detection_attempts.ps1.epp** which is preventing the conflict_detection_attempts overwritten param value to set.

@karmafeast Can you please allow me developer privileges to I can fix that and submit a merge request?

**Comment by karmafeast** [comment]
corrected in merged PR https://github.com/karmafeast/win_dhcp_server/pull/2

release 1.0.4 is up on forge. thank you @amitp18
